### ISSUE TITLE
Add some Codechef Solutions .

### ISSUE THREAD

**Issue by sumitt194** [sumitt194/Codeforces-Solutions#3]
Add some Codechef Solutions in a separate folder. Please follow contribution guidelines

**Comment by sumitt194** [comment]
@RgnDunes @Adi9235 You both can work on this. But pls try to provide solution for different problems. I mean i don't need solutions for 1000 problems. This is a contribution repository. You both can provide solutions for at least 50 and max 60 problems. I think in this way there is a less chance of redundancy and will also make scope for other people's contribution.

**Comment by RgnDunes** [comment]
@sumitt194 added the [PR](https://github.com/sumitt194/Codeforces-Solutions/pull/5) please review.

**Comment by RgnDunes** [comment]
@sumitt194  ^
