### ISSUE TITLE
Add solutions for Binary Search from Interviewbit 

### ISSUE THREAD

**Issue by sumitt194** [sumitt194/Codeforces-Solutions#47]

**Comment by Princeton21** [comment]
I can work on this

**Comment by UtsavUpadhyay08** [comment]
hey @sumitt194 I would like to contribute to this by adding solution to this problem. Please assign this to me.

**Comment by sabhisharma-ise** [comment]
Can you please assign this issue to me?

**Comment by sumitt194** [comment]
Done
